### ISSUE TITLE
Pressure and Dew Point

### ISSUE THREAD

**Issue by harneyphoto** [sathyarajv/MMM-OpenmapWeather#11]
Love this module. Such an improvement on the basic weather module.  I have one question though, how easy is it to include barometric pressure and Dew point. Both items are available from OpenWeather but as I have VERY limited coding skills, is it possible to include them under wind and humidity.  I notice only one module includes pressure reading but as I am using a 7inch touch screen, they dont fit on MY screen and I prefer this layout better.

AS a wave.ocean photographer, the pressure and dew point are items I check to see where Its worthwhile getting in the water as I can get a clear idea on conditions (I live an hour from the ocean)

Cheers

**Comment by sathyarajv** [comment]
@harneyphoto Thank you for your feedback. I'll try to include this part of next update.

**Comment by sathyarajv** [comment]
@harneyphoto Dew Point and Pressure values are available now. Please try the latest version.
