### ISSUE TITLE
New MM2 Update

### ISSUE THREAD

**Issue by fmmcyyc** [sathyarajv/MMM-OpenmapWeather#12]
Hi once the new update for MM2 was pushed, I keep getting "Feels like {DEGREE} " and the correct temperature. 
![image](https://user-images.githubusercontent.com/51055583/114315938-8a519c00-9abe-11eb-9d26-62f7355bc289.png)

How do i eliminate the {DEGREE}

Thanks

**Comment by Ris119** [comment]
I'm having the same exact issue. Would love to know the fix

**Comment by sathyarajv** [comment]
Thanks for the update, this is fixed now. Please try the latest version.
