### ISSUE TITLE
Openweather Temp is off

### ISSUE THREAD

**Issue by Dresch360** [sathyarajv/MMM-OpenmapWeather#13]
Great module

Temperatures are off by over 10 degrees. Unable to access location ID (missing Openweather URL). Is there any way to include lat and lon for location? Wasn't able to make it work.

http://openweathermap.org/help/city_list.txt goes to "Page not found"

Thanks

**Comment by sathyarajv** [comment]
You can find the location/City ID in the Openweathermap website by searching with the city name, the city ID will be available on the url
![image](https://user-images.githubusercontent.com/9957258/134817753-70995153-adfe-41e7-94e8-cb85d2ddac17.png)
