### ISSUE TITLE
showWindDirectionAsArrow doesn't work

### ISSUE THREAD

**Issue by Mysh3ll** [sathyarajv/MMM-OpenmapWeather#3]
Hi,
I set the config param showWindDirectionAsArrow  to true, but the fontawesome icon doesn't appear. Instead I have an empty square. But if i change the value of 
`<i class="fa fa-long-arrow-down" style="transform:rotate(170deg);"></i> `
by 
`<i class="fas fa-long-arrow-alt-down" style="transform:rotate(170deg);"></i>`
it works !

Any idea?

**Comment by sathyarajv** [comment]
Tried this property from config its working fine, try with latest MM & module installation

{
		module: "MMM-OpenmapWeather",
		position: "top_left",	// This can be any of the regions.Best results in left or right regions.
		config: {
			location: "Seattle,US",
			locationID: "5809844", //Location ID from http://openweathermap.org/help/city_list.txt
			appid: "a",  //openweathermap.org API key
      			colorIcon: true,
      			showWindDirectionAsArrow: true
		}
	}
![UI](https://user-images.githubusercontent.com/9957258/59140599-e1333b00-8954-11e9-9b60-a642ab407273.jpg)
