### ISSUE TITLE
One image not showing

### ISSUE THREAD

**Issue by ghost** [sathyarajv/MMM-OpenmapWeather#8]
Failed to load resource: the server responded with a status of 404 (Not Found) undefined
 
 it probably has something to do with the last image you have commented out in the iconimagetable, whats up with that?

**Comment by JoshuaShelswell** [comment]
0|mm       |     at Function.Module._load (internal/modules/cjs/loader.js:560:12)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:685:19)
0|mm       |     at require (internal/modules/cjs/helpers.js:16:16)
0|mm       |     at loadConfig (/home/pi/MagicMirror/js/app.js:70:12)
0|mm       |     at App.start (/home/pi/MagicMirror/js/app.js:217:3)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:129:7)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:786:30)
0|mm       | [9252:1217/052005.189082:ERROR:gles2_cmd_decoder.cc(18538)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
0|mm       | [9252:1217/052005.189182:ERROR:gles2_cmd_decoder.cc(18559)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
0|mm       | [9252:1217/052005.189276:ERROR:gles2_cmd_decoder.cc(10749)] [.DisplayCompositor]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0|mm       | [9252:1217/052005.189506:ERROR:gles2_cmd_decoder.cc(18582)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
0|mm       | [9252:1217/052005.189615:ERROR:gles2_cmd_decoder.cc(18538)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
0|mm       | [9252:1217/052005.189647:ERROR:gles2_cmd_decoder.cc(18559)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
0|mm       | [9252:1217/052005.189749:ERROR:gles2_cmd_decoder.cc(10749)] [.DisplayCompositor]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0|mm       | [9252:1217/052005.189868:ERROR:gles2_cmd_decoder.cc(18582)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image

**Comment by JoshuaShelswell** [comment]
i fixed it by changing your js file, removed the comment in your line and renamed the file in 50n, then i went to your icons folder and picked nt_partlysunny.jpg (since its not used) and renamed it to wi_night_alt_cloudy_windy.png  error fixed

		iconImageTable: {
			"01d": "sunny.png",
			"02d": "partlysunny.png",
			"03d": "partlycloudy.png",
			"04d": "cloudy.png",
			"09d": "sleet.png",
			"10d": "rain.png",
			"11d": "tstorms.png",
			"13d": "snow.png",
			"50d": "fog.png",
			"01n": "nt_clear.png",
			"02n": "nt_cloudy.png",
			"03n": "nt_mostlycloudy.png",
			"04n": "cloudy.png",
			"09n": "nt_sleet.png",
			"10n": "nt_rain.png",
			"11n": "nt_tstorms.png",
			"13n": "nt_snow.png",
			"50n": "wi_night_alt_cloudy_windy.png"
		},
	},

**Comment by sathyarajv** [comment]
@ghost - Thanks for your information. I've added the new image in the latest commit.
